[build]
  publish = "public"
  command = "npm run build"
  functions = "functions/"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
